/**
 * Release Report Generator — WP-6.2
 * Formats release-report.md, release-summary.json, and certification summaries.
 */

import * as fs from 'fs';
import * as path from 'path';
import { ReleaseMetadata } from './release-metadata';
import { CertificationResult } from './certification-engine';

export class ReleaseReportGenerator {
  private projectRoot: string;
  private releaseDir: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.releaseDir = path.join(projectRoot, 'dist-release');
  }

  /**
   * Generates release-report.md under dist-release/
   */
  public generateMarkdownReport(metadata: ReleaseMetadata, certResult: CertificationResult, channel: string = 'GA'): string {
    if (!fs.existsSync(this.releaseDir)) {
      fs.mkdirSync(this.releaseDir, { recursive: true });
    }

    const reportPath = path.join(this.releaseDir, 'release-report.md');
    const badge = certResult.overallPassed ? '✅ CERTIFIED RELEASE' : '❌ CERTIFICATION FAILED';

    const content = `# SPPG Companion — Production Release Report

## Status: ${badge}

- **Release Version**: \`${metadata.version}\`
- **Target Channel**: \`${channel}\`
- **Build Number**: \`${metadata.buildNumber}\`
- **Build Timestamp**: \`${metadata.buildTimestamp}\`
- **Git Commit Hash**: \`${metadata.gitCommitHash}\` (\`${metadata.gitCommitFull}\`)
- **Git Branch**: \`${metadata.gitBranch}\`
- **Target Platform**: Chrome Extension (Manifest V3)

---

## Metric Summaries

| Metric Category | Detail | Value |
| :--- | :--- | :--- |
| **Zip Package Size** | Compressed Extension ZIP | ${metadata.bundleMetrics?.zipSizeFormatted || 'N/A'} |
| **Uncompressed Size** | Total Extracted Directory Size | ${
      metadata.bundleMetrics ? `${(metadata.bundleMetrics.uncompressedSizeBytes / (1024 * 1024)).toFixed(2)} MB` : 'N/A'
    } |
| **Bundle File Count** | Total Assets in ZIP | ${metadata.bundleMetrics?.fileCount || 0} files |
| **Repository Health** | Clean Git State | ${metadata.repositoryHealth.isClean ? 'Clean (0 modifications)' : 'Dirty'} |
| **Toolchain Node.js** | Runtime Environment | ${metadata.nodeVersion} |
| **Toolchain Vite** | Bundler Engine | ${metadata.viteVersion} |

---

## Certification Checklist Summary

- **Total Quality Gates Evaluated**: ${certResult.totalGates}
- **Passed Gates**: ${certResult.passedGates} / ${certResult.totalGates}
- **Compliance Status**: ${certResult.overallPassed ? 'FULLY COMPLIANT' : 'NON-COMPLIANT'}

Detailed checklist available at [certification-report.md](file:///${path.join(this.releaseDir, 'certification-report.md').replace(/\\/g, '/')}).

---
*Generated by Production Release Framework (WP-6.2)*
`;

    fs.writeFileSync(reportPath, content, 'utf8');
    return reportPath;
  }

  /**
   * Generates machine-readable release-summary.json under dist-release/
   */
  public generateJsonSummary(metadata: ReleaseMetadata, certResult: CertificationResult, channel: string = 'GA'): string {
    if (!fs.existsSync(this.releaseDir)) {
      fs.mkdirSync(this.releaseDir, { recursive: true });
    }

    const summaryPath = path.join(this.releaseDir, 'release-summary.json');
    const summaryData = {
      project: metadata.projectName,
      version: metadata.version,
      channel,
      buildNumber: metadata.buildNumber,
      timestamp: metadata.buildTimestamp,
      gitCommit: metadata.gitCommitHash,
      gitBranch: metadata.gitBranch,
      certification: {
        passed: certResult.overallPassed,
        score: `${certResult.passedGates}/${certResult.totalGates}`,
        certifiedAt: certResult.certifiedAt
      },
      bundleMetrics: metadata.bundleMetrics
    };

    fs.writeFileSync(summaryPath, JSON.stringify(summaryData, null, 2), 'utf8');
    return summaryPath;
  }
}
