/**
 * Distribution Report Generator — WP-6.3
 * Formats distribution-report.md, distribution-summary.json, and store-readiness-report.md.
 */

import * as fs from 'fs';
import * as path from 'path';
import { StoreReadinessResult } from './distribution-validator';
import { AssetValidationResult } from './asset-validator';
import { CompatibilityResult } from './compatibility-validator';

export class DistributionReportGenerator {
  private projectRoot: string;
  private releaseDir: string;

  constructor(projectRoot: string) {
    this.projectRoot = projectRoot;
    this.releaseDir = path.join(projectRoot, 'dist-release');
  }

  /**
   * Generates distribution-report.md
   */
  public generateDistributionReport(
    storeResult: StoreReadinessResult,
    assetResult: AssetValidationResult,
    compatResult: CompatibilityResult
  ): string {
    const reportPath = path.join(this.releaseDir, 'distribution-report.md');
    const badge = storeResult.valid && assetResult.allRequiredPassed ? '✅ APPROVED FOR DISTRIBUTION' : '⚠️ ISSUES DETECTED';

    const content = `# SPPG Companion — Distribution & Store Readiness Report

## Status: ${badge}

- **Extension Version**: \`${storeResult.extensionVersion}\`
- **Manifest Version**: \`MV${storeResult.manifestVersion}\`
- **Target Profile**: \`${storeResult.profile.toUpperCase()}\`
- **Generated At**: \`${new Date().toISOString()}\`

---

## Executive Summary

| Verification Module | Status | Score / Metrics |
| :--- | :--- | :--- |
| **Store Readiness** | ${storeResult.valid ? '✅ VALID' : '❌ INVALID'} | ${storeResult.issues.length} issues reported |
| **Asset Verification** | ${assetResult.allRequiredPassed ? '✅ VALID' : '❌ INVALID'} | ${assetResult.passedCount}/${assetResult.totalAssetsChecked} assets verified |
| **Browser Compatibility** | ${compatResult.overallCompatible ? '✅ COMPATIBLE' : '❌ INCOMPATIBLE'} | Chrome 102+ / Edge MV3 |

---

## Store Metadata Highlights
- **Privacy Policy**: Referenced in \`store-metadata.json\`
- **Support URL**: GitHub Issues tracking
- **Target Platforms**: Chrome Web Store, Microsoft Edge Add-ons, Enterprise Policy Sideloading

---
*Generated by Distribution Packaging Framework (WP-6.3)*
`;

    fs.writeFileSync(reportPath, content, 'utf8');
    return reportPath;
  }

  /**
   * Generates machine-readable distribution-summary.json
   */
  public generateSummaryJson(
    storeResult: StoreReadinessResult,
    assetResult: AssetValidationResult,
    compatResult: CompatibilityResult
  ): string {
    const summaryPath = path.join(this.releaseDir, 'distribution-summary.json');
    const summaryData = {
      version: storeResult.extensionVersion,
      manifestVersion: storeResult.manifestVersion,
      profile: storeResult.profile,
      timestamp: new Date().toISOString(),
      storeReadiness: {
        valid: storeResult.valid,
        issueCount: storeResult.issues.length
      },
      assetVerification: {
        allPassed: assetResult.allRequiredPassed,
        passedCount: assetResult.passedCount,
        totalChecked: assetResult.totalAssetsChecked
      },
      compatibility: {
        overallCompatible: compatResult.overallCompatible,
        minChromeVersion: compatResult.minChromeVersion
      }
    };

    fs.writeFileSync(summaryPath, JSON.stringify(summaryData, null, 2), 'utf8');
    return summaryPath;
  }

  /**
   * Generates store-readiness-report.md
   */
  public generateStoreReadinessReport(storeResult: StoreReadinessResult, assetResult: AssetValidationResult): string {
    const reportPath = path.join(this.releaseDir, 'store-readiness-report.md');
    const badge = storeResult.valid ? '✅ STORE SUBMISSION READY' : '❌ ACTION REQUIRED';

    let markdown = `# Chrome Web Store Submission Readiness Report

## Status: ${badge}

- **Checked At**: ${new Date().toISOString()}
- **Profile**: \`${storeResult.profile}\`

---

## Store Checklist Audit Items

| Rule ID | Category | Severity | Status | Description / Finding |
| :--- | :--- | :--- | :--- | :--- |
`;

    if (storeResult.issues.length === 0) {
      markdown += `| **STORE-000** | Compliance | \`INFO\` | ✅ PASS | All mandatory Chrome Web Store developer policy checks passed. |\n`;
    } else {
      for (const issue of storeResult.issues) {
        const icon = issue.severity === 'CRITICAL' || issue.severity === 'HIGH' ? '❌ FAIL' : '⚠️ WARN';
        markdown += `| **${issue.ruleId}** | ${issue.category} | \`${issue.severity}\` | ${icon} | ${issue.message} |\n`;
      }
    }

    markdown += `
---

## Required Icon Matrix Audit
- Required Icons (16x16, 48x48, 128x128): ${assetResult.allRequiredPassed ? '✅ ALL PRESENT' : '❌ MISSING'}
- Total Assets Verified: ${assetResult.passedCount} / ${assetResult.totalAssetsChecked}
`;

    fs.writeFileSync(reportPath, markdown, 'utf8');
    return reportPath;
  }
}
